name: Run integration tests

on:
  workflow_dispatch:
  # TODO add trigger

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start services with docker compose
        uses: isbang/compose-action@v1.4.1

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install pip dependencies
        run: pip install requests pytest

      - name: Run tests
        run: pytest tests/integration_tests -vvb

